library("sqldf")
power<-read.csv.sql("household_power_consumption.txt", sql="select * from file where Date in ('1/2/2007','2/2/2007')", header=T, sep=";")
dateTime<- as.POSIXlt(paste(as.Date(power$Date, format="%d/%m/%Y"), power$Time, sep=" "))
png(filename = "plot3.png", width = 480, height = 480, units="px")
plot(dateTime, power[,7], type = "l")
lines(dateTime, power[,8], type = "l", col="red")
lines(dateTime, power[,9], type = "l", col="blue")
legend('topright', legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5) ,col=c("black", "red", "blue"))
dev.off()